server:
  port: 8092
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password: ''
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: 'true'